Repository likelion-LIKIT/Back-end, pull requests merged in 2023-03, with the labels that each got.

#1 Feature/File create get method and fix contentType of pdf
  build.gradle
  src/main/java/com/likelion/likit/diary/DiaryService.java
  src/main/java/com/likelion/likit/exception/ExceptionEnum.java
  src/main/java/com/likelion/likit/file/FileController.java
  src/main/java/com/likelion/likit/file/FileHandler.java
  src/main/java/com/likelion/likit/file/FileService.java
  src/main/java/com/likelion/likit/file/dto/FileResDto.java
  src/main/java/com/likelion/likit/file/repository/JpaFileRepository.java
Labels: 🔥 bug, 🔨 기능추가

#3 Feature/diary change response of post, patch methods + create delete method to delete a diary of a particular + create diary like, unlike functions id
  src/main/java/com/likelion/likit/diary/DiaryController.java
  src/main/java/com/likelion/likit/diary/DiaryService.java
  src/main/java/com/likelion/likit/diary/dto/DiaryResDto.java
  src/main/java/com/likelion/likit/diary/entity/Diary.java
  src/main/java/com/likelion/likit/diary/entity/LikeMembers.java
  src/main/java/com/likelion/likit/diary/repository/JpaDiaryLikeRepository.java
Labels: 🔨 기능추가

#8 Feature/file change file to diaryfile & move to diary
  gradlew.bat
  src/main/java/com/likelion/likit/diary/DiaryController.java
  src/main/java/com/likelion/likit/diary/DiaryFileHandler.java
  src/main/java/com/likelion/likit/diary/DiaryService.java
  src/main/java/com/likelion/likit/diary/dto/DiaryReqDto.java
  src/main/java/com/likelion/likit/diary/dto/DiaryResDto.java
  src/main/java/com/likelion/likit/diary/dto/DiaryThumbnailDto.java
  src/main/java/com/likelion/likit/diary/entity/Diary.java
  src/main/java/com/likelion/likit/diary/entity/DiaryFile.java
  src/main/java/com/likelion/likit/diary/repository/JpaDiaryFileRepository.java
  src/main/java/com/likelion/likit/file/FileController.java
  src/main/java/com/likelion/likit/file/FileDto.java
  src/main/java/com/likelion/likit/file/FileService.java
  src/main/java/com/likelion/likit/file/dto/FileResDto.java
  src/main/java/com/likelion/likit/file/repository/JpaFileRepository.java
  src/main/resources/application.yml
Labels: ⚒ 기능 개선

#9 Feature/file change how content-type is stored & create download file function
  src/main/java/com/likelion/likit/diary/DiaryController.java
  src/main/java/com/likelion/likit/diary/DiaryFileHandler.java
  src/main/java/com/likelion/likit/diary/DiaryService.java
Labels: 🔨 기능추가

#10 fix(File) : fix bug that cannot save files
  src/main/java/com/likelion/likit/diary/DiaryFileHandler.java
Labels: 🔥 bug

#13 Feature/file
  src/main/java/com/likelion/likit/diary/DiaryController.java
  src/main/java/com/likelion/likit/diary/DiaryService.java
  src/main/java/com/likelion/likit/diary/repository/JpaDiaryFileRepository.java
Labels: ⚒ 기능 개선

#12 feat(Notice) : create get method to find file with file name
  src/main/java/com/likelion/likit/notice/NoticeController.java
  src/main/java/com/likelion/likit/notice/NoticeService.java
  src/main/java/com/likelion/likit/notice/repository/JpaNoticeFileRepository.java
Labels: 🔥 bug, ⚒ 기능 개선

#16 Feature/member change membership information to be inquired by studentId
  src/main/java/com/likelion/likit/member/MemberController.java
  src/main/java/com/likelion/likit/member/MemberService.java
  src/main/resources/application.yml
Labels: 🔨 기능추가

#21 Feature/diary create a temporary save function
  src/main/java/com/likelion/likit/diary/DiaryController.java
  src/main/java/com/likelion/likit/diary/DiaryService.java
  src/main/java/com/likelion/likit/diary/dto/DiaryReqDto.java
  src/main/java/com/likelion/likit/diary/dto/DiaryResDto.java
  src/main/java/com/likelion/likit/diary/entity/Diary.java
  src/main/java/com/likelion/likit/diary/repository/JpaDiaryFileRepository.java
  src/main/java/com/likelion/likit/diary/repository/JpaDiaryLikeRepository.java
  src/main/java/com/likelion/likit/diary/repository/JpaDiaryRepository.java
  src/main/java/com/likelion/likit/file/repository/JpaImageFileRepository.java
  src/main/java/com/likelion/likit/notice/repository/JpaNoticeFileRepository.java
  src/main/java/com/likelion/likit/notice/repository/JpaNoticeLikeRepository.java
  src/main/java/com/likelion/likit/token/JpaTokenRepository.java
Labels: 🔥 bug, 🔨 기능추가

#22 Feature/notice save image & return url & temporary save funtion
  src/main/java/com/likelion/likit/notice/NoticeController.java
  src/main/java/com/likelion/likit/notice/NoticeFileHandler.java
  src/main/java/com/likelion/likit/notice/NoticeService.java
  src/main/java/com/likelion/likit/notice/dto/NoticeReqDto.java
  src/main/java/com/likelion/likit/notice/dto/NoticeResDto.java
  src/main/java/com/likelion/likit/notice/entity/Notice.java
  src/main/java/com/likelion/likit/notice/entity/NoticeLikeMembers.java
  src/main/java/com/likelion/likit/notice/repository/JpaNoticeFileRepository.java
  src/main/java/com/likelion/likit/notice/repository/JpaNoticeRepository.java
Labels: 🔨 기능추가

#23 Refactor refactor member position & categories
  src/main/java/com/likelion/likit/member/MemberController.java
  src/main/java/com/likelion/likit/member/MemberService.java
  src/main/java/com/likelion/likit/member/dto/MemberReqDto.java
  src/main/java/com/likelion/likit/member/dto/MemberResDto.java
  src/main/java/com/likelion/likit/member/dto/MemberUpdateReqDto.java
  src/main/java/com/likelion/likit/member/dto/PositionUpdateDto.java
  src/main/java/com/likelion/likit/member/entity/Category.java
  src/main/java/com/likelion/likit/member/entity/Major.java
  src/main/java/com/likelion/likit/member/entity/MemberDetail.java
  src/main/java/com/likelion/likit/member/entity/Position.java
  src/main/java/com/likelion/likit/member/repository/JpaMemberDetailRepository.java
  src/main/java/com/likelion/likit/member/repository/JpaPositionRepository.java
  src/main/java/com/likelion/likit/notice/entity/Category.java
Labels: ⚒ 기능 개선

#24 feat(Diary) : create a return function for the list of likes pressed
  src/main/java/com/likelion/likit/diary/DiaryController.java
  src/main/java/com/likelion/likit/diary/DiaryService.java
Labels: 🔨 기능추가

#27 feat(Activity) : activity settings
  src/main/java/com/likelion/likit/activity/ActivityController.java
  src/main/java/com/likelion/likit/activity/ActivityService.java
  src/main/java/com/likelion/likit/activity/dto/ActivityReqDto.java
  src/main/java/com/likelion/likit/activity/dto/ActivityResDto.java
  src/main/java/com/likelion/likit/activity/entity/Activity.java
  src/main/java/com/likelion/likit/activity/entity/ActivityFile.java
  src/main/java/com/likelion/likit/activity/entity/ActivityURL.java
  src/main/java/com/likelion/likit/activity/entity/ProjectJoin.java
  src/main/java/com/likelion/likit/activity/repository/JpaActivityFileRepository.java
  src/main/java/com/likelion/likit/activity/repository/JpaActivityRepository.java
  src/main/java/com/likelion/likit/activity/repository/JpaActivityURLRepository.java
  src/main/java/com/likelion/likit/activity/repository/JpaProjectJoin.java
  src/main/resources/application.yml
Labels: 🔨 기능추가, ⚒ 기능 개선

#29 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#30 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#31 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#32 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#33 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#34 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/WebConfig.java
Labels: 🔥 bug

#35 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#36 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
  src/main/java/com/likelion/likit/config/WebConfig.java
Labels: 🔥 bug

#37 fix(Config) : fix cors error
  src/main/java/com/likelion/likit/config/SecurityConfig.java
Labels: 🔥 bug

#38 fix(Notice) : fix null file error
  src/main/java/com/likelion/likit/notice/NoticeFileHandler.java
Labels: 🔥 bug
